# Spring Boot Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.ecoomerce.sportscenter: DEBUG

server:
  port: 8081

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sonmaidb;encrypt=true;trustServerCertificate=true
    username: sa2
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  application:
    name: SonMaiApp
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456

# VNPay Configuration
vnpay:
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  tmn-code: YOUR_TMN_CODE
  hash-secret: YOUR_HASH_SECRET
  return-url: http://localhost:4200/payment-result
  version: 2.1.0
